### ISSUE TITLE
Animation beendet wenn Lonk springt

### ISSUE THREAD

**Issue by PiotrMi** [PiotrMi/LonksAdventure#1]
wenn ich danach weitergehe geht die animation auch nicht mehr weiter

**Comment by PiotrMi** [comment]
Erst nach gut 3 sekunden wenn ich stehen geblieben bin, bewegen sich die beine kurz und wenn ich mich dann bewege spielt die animation wieder wie gewohnt ab

**Comment by Elbcore3** [comment]
Bug Herkunft Gefunden, wird im nächsten push gefixt.

**Comment by PiotrMi** [comment]
+1 :B

**Comment by Elbcore3** [comment]
:B

**Comment by Elbcore3** [comment]
Fixed. Issue Closed.
